[tools]
bun = "1.3"
node = "25.0"
python = "3.14"
uv = "0.9.4"

[env]
_.file = '.env'

[tasks.makemigrations]
description = "Make backend migrations"
dir = "backend"
run = "uv run manage.py makemigrations"

[tasks.migrate]
description = "Apply migrations"
dir = "backend"
wait_for = "makemigrations"
run = "uv run manage.py migrate"

[tasks."dev:backend"]
description = "Run the backend Django server"
dir = "backend"
depends = ["migrate"]
run = "uv run manage.py runserver"

[tasks."dev:frontend"]
description = "Run the frontend Bun server"
dir = "frontend"
run = "bun run dev"

[tasks.dev]
description = "Start both frontend and backend dev servers"
depends = ["dev:*"]

